/******************************************************************************
*
* Copyright (C) 2023 [Your Company Name]
*
* Engineer:      Kim Gwajang (Lead Engineer)
* Create Date:   2025/05/27
*
* Description:   Firmware for APB-based RGB LED Controller.
*                - Receives commands via UART.
*                - Controls 2 RGB LEDs by writing to the custom PWM controller's registers.
*                - Reads register values to report current LED status.
*
******************************************************************************/

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "xparameters.h"  // Hardware parameter definitions
#include "xuartlite.h"    // UART Lite driver
#include "xil_io.h"       // Xilinx I/O functions (Xil_Out32, Xil_In32)
#include "xil_printf.h"   // Xilinx standard I/O for printing

//================================================================
// 1. Hardware Constants Definition
//================================================================
// Base address of the AXI-to-APB Bridge, connected to our PWM controller.
// This value is imported from xparameters.h, generated by Vivado.
#define PWM_CTRL_BASEADDR   XPAR_APB_M_0_BASEADDR

// Register map offsets, matching the Verilog design
#define REG_OFFSET_LED0_R   0x00
#define REG_OFFSET_LED0_G   0x04
#define REG_OFFSET_LED0_B   0x08
#define REG_OFFSET_LED1_R   0x0C
#define REG_OFFSET_LED1_G   0x10
#define REG_OFFSET_LED1_B   0x14

// UART Device ID from xparameters.h
#define UART_DEVICE_ID      XPAR_UARTLITE_0_DEVICE_ID

// Command buffer size
#define CMD_BUFFER_SIZE     64

//================================================================
// 2. Global Variables
//================================================================
static XUartLite UartLiteInst;  // UART Lite driver instance

//================================================================
// 3. Function Prototypes
//================================================================
int initialize_peripherals();
int read_line(char *buffer, int len);
void process_command(char *cmd_buffer);

//================================================================
// 4. Main Function
//================================================================
int main() {
    char cmd_buffer[CMD_BUFFER_SIZE];
    int status;

    status = initialize_peripherals();
    if (status != XST_SUCCESS) {
        xil_printf("Error: Peripheral initialization failed.\r\n");
        return XST_FAILURE;
    }

    while (1) {
        xil_printf("> "); // Print command prompt
        read_line(cmd_buffer, CMD_BUFFER_SIZE);
        process_command(cmd_buffer);
    }

    return 0; // Should not be reached
}

//================================================================
// 5. Peripheral Initialization Function
//================================================================
int initialize_peripherals() {
    int status;
    u32 reg_offsets[] = {
        REG_OFFSET_LED0_R, REG_OFFSET_LED0_G, REG_OFFSET_LED0_B,
        REG_OFFSET_LED1_R, REG_OFFSET_LED1_G, REG_OFFSET_LED1_B
    };

    // Initialize UART
    status = XUartLite_Initialize(&UartLiteInst, UART_DEVICE_ID);
    if (status != XST_SUCCESS) {
        return XST_FAILURE;
    }

    // Flush any pre-existing data in the UART FIFO
    XUartLite_ResetFifos(&UartLiteInst);

    // Print welcome message as required by the specification
    xil_printf("RGB LED Control Test Program\r\n");
    xil_printf("----------------------------------\r\n");

    // Initialize all LEDs to OFF (duty cycle = 0)
    for (int i = 0; i < 6; i++) {
        Xil_Out32(PWM_CTRL_BASEADDR + reg_offsets[i], 0);
    }
    xil_printf("All LEDs initialized to OFF.\r\n");

    return XST_SUCCESS;
}

//================================================================
// 6. UART Line Reading Helper Function
//================================================================
int read_line(char *buffer, int len) {
    int count = 0;
    char c;

    while (count < len - 1) {
        c = XUartLite_RecvByte(XPAR_UARTLITE_0_BASEADDR);

        if (c == '\r' || c == '\n') { // Enter key
            buffer[count] = '\0';
            xil_printf("\r\n");
            return count;
        } else if (c == '\b' || c == 127) { // Backspace
            if (count > 0) {
                count--;
                xil_printf("\b \b"); // Erase character on terminal
            }
        } else {
            buffer[count++] = c;
            XUartLite_Send(&UartLiteInst, (u8 *)&c, 1); // Echo character
        }
    }
    buffer[count] = '\0';
    return count;
}


//================================================================
// 7. Command Processing Function
//================================================================
void process_command(char *cmd_buffer) {
    char *argv[5]; // Max 4 arguments + 1 for safety
    int argc = 0;
    char *token;

    // Parse the command string by spaces using strtok
    token = strtok(cmd_buffer, " ");
    while (token != NULL && argc < 5) {
        argv[argc++] = token;
        token = strtok(NULL, " ");
    }

    if (argc == 0) {
        return; // Empty command
    }

    // Branch based on number of arguments
    if (argc == 4) { // Case 1: Set Color (e.g., "0 100 20 50")
        int led_num = atoi(argv[0]);
        int r_val = atoi(argv[1]);
        int g_val = atoi(argv[2]);
        int b_val = atoi(argv[3]);

        // Input validation
        if ((led_num != 0 && led_num != 1) ||
            (r_val < 0 || r_val > 255) ||
            (g_val < 0 || g_val > 255) ||
            (b_val < 0 || b_val > 255)) {
            xil_printf("Error: Invalid arguments. Use: (LED# 0-1) (R G B 0-255)\r\n");
            return;
        }

        // Calculate register addresses and write values
        u32 base_offset = (led_num == 0) ? 0 : (REG_OFFSET_LED1_R);
        Xil_Out32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_R, r_val);
        Xil_Out32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_G, g_val);
        Xil_Out32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_B, b_val);

        xil_printf("OK: LED %d set to R:%d, G:%d, B:%d\r\n", led_num, r_val, g_val, b_val);

    } else if (argc == 1) { // Case 2: Get Status (e.g., "0")
        int led_num = atoi(argv[0]);

        if (led_num != 0 && led_num != 1) {
            xil_printf("Error: Invalid LED number. Use 0 or 1.\r\n");
            return;
        }

        // Calculate register addresses and read values
        u32 base_offset = (led_num == 0) ? 0 : (REG_OFFSET_LED1_R);
        int r_val = Xil_In32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_R);
        int g_val = Xil_In32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_G);
        int b_val = Xil_In32(PWM_CTRL_BASEADDR + base_offset + REG_OFFSET_LED0_B);

        // Print in the specified format
        xil_printf("RGB %d : R-%d, G-%d, B-%d\r\n", led_num, r_val, g_val, b_val);

    } else { // Invalid command format
        xil_printf("Error: Invalid command format.\r\n");
        xil_printf("Usage:\r\n");
        xil_printf("  Set color: <led_num> <r> <g> <b>\r\n");
        xil_printf("  Get status: <led_num>\r\n");
    }
}
