`timescale 1ns / 1ps

module system_top (
    // System Inputs
    input  wire        i_clk_100mhz,
    input  wire        i_resetn,

    // UART Interface
    input  wire        i_uart_rxd,
    output wire        o_uart_txd,
    
    // RGB LED PWM Outputs
    output wire [5:0]  o_rgb_pwm // To be connected to FPGA pins for 2 RGB LEDs
);

    // Internal wires for APB connection
    wire [31:0] w_apb_paddr;
    wire        w_apb_psel;
    wire        w_apb_penable;
    wire        w_apb_pwrite;
    wire [31:0] w_apb_pwdata;
    wire [31:0] w_apb_prdata;
    wire        w_apb_pready;
    wire        w_apb_pslverr;

    // 1. Instantiate the Block Design Wrapper
    // Note: Port names must match the actual wrapper file generated by Vivado.
    // Here, we assume the APB bridge instance in the BD is named 'axi_apb_bridge_0'.
    apb_rgb_led_wrapper u_apb_rgb_led_wrapper (
        .Clk       (i_clk_100mhz),
        .reset_rtl_0           (i_resetn),
        .uart_rtl_0_rxd     (i_uart_rxd),
        .uart_rtl_0_txd     (o_uart_txd),
        
        // APB Master Interface from the Bridge
        .APB_M_0_paddr    (w_apb_paddr),
        .APB_M_0_psel     (w_apb_psel),
        .APB_M_0_penable  (w_apb_penable),
        .APB_M_0_pwrite   (w_apb_pwrite),
        .APB_M_0_pwdata   (w_apb_pwdata),
        .APB_M_0_prdata   (w_apb_prdata),
        .APB_M_0_pready   (w_apb_pready),
        .APB_M_0_pslverr  (w_apb_pslverr)
    );

    // 2. Instantiate the custom PWM Controller
    rgb_pwm_controller u_rgb_pwm_controller (
        .PCLK           (i_clk_100mhz), // APB clock is the same as system clock
        .PRESETn        (i_resetn),

        // Connecting APB signals from the bridge to the slave controller
        .PADDR          (w_apb_paddr),
        .PSEL           (w_apb_psel),
        .PENABLE        (w_apb_penable),
        .PWRITE         (w_apb_pwrite),
        .PWDATA         (w_apb_pwdata),
        .PRDATA         (w_apb_prdata),
        .PREADY         (w_apb_pready),
        .PSLVERR        (w_apb_pslverr),

        // PWM Output
        .o_pwm_ch       (o_rgb_pwm)
    );

endmodule
